### ISSUE TITLE
install knn fails 

### ISSUE THREAD

**Issue by TommasoBendinelli** [mentian/object-posenet#1]
when running python3 setup.py install --user in the knn folder I get the following error:

(env) labuser@labuser-desktop:~/repos/object-posenet/lib/knn$ python3 setup.py install       
running install
running bdist_egg
running egg_info
writing knn_pytorch.egg-info/PKG-INFO
writing dependency_links to knn_pytorch.egg-info/dependency_links.txt
writing top-level names to knn_pytorch.egg-info/top_level.txt
reading manifest file 'knn_pytorch.egg-info/SOURCES.txt'
writing manifest file 'knn_pytorch.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'knn_pytorch' extension
Emitting ninja build file /home/labuser/repos/object-posenet/lib/knn/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ -MMD -MF /home/labuser/repos/object-posenet/lib/knn/build/temp.linux-x86_64-3.6/home/labuser/repos/object-posenet/lib/knn/src/vision.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/labuser/repos/object-posenet/lib/knn/src -I/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include -I/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/TH -I/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/labuser/repos/object-posenet/env/include -I/usr/include/python3.6m -c -c /home/labuser/repos/object-posenet/lib/knn/src/vision.cpp -o /home/labuser/repos/object-posenet/lib/knn/build/temp.linux-x86_64-3.6/home/labuser/repos/object-posenet/lib/knn/src/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=knn_pytorch -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/labuser/repos/object-posenet/lib/knn/build/temp.linux-x86_64-3.6/home/labuser/repos/object-posenet/lib/knn/src/vision.o 
c++ -MMD -MF /home/labuser/repos/object-posenet/lib/knn/build/temp.linux-x86_64-3.6/home/labuser/repos/object-posenet/lib/knn/src/vision.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/labuser/repos/object-posenet/lib/knn/src -I/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include -I/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/TH -I/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/labuser/repos/object-posenet/env/include -I/usr/include/python3.6m -c -c /home/labuser/repos/object-posenet/lib/knn/src/vision.cpp -o /home/labuser/repos/object-posenet/lib/knn/build/temp.linux-x86_64-3.6/home/labuser/repos/object-posenet/lib/knn/src/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=knn_pytorch -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
In file included from /home/labuser/repos/object-posenet/lib/knn/src/vision.cpp:1:0:
/home/labuser/repos/object-posenet/lib/knn/src/knn.h: In function 'int knn(at::Tensor&, at::Tensor&, at::Tensor&)':
/home/labuser/repos/object-posenet/lib/knn/src/knn.h:23:38: warning: 'T* at::Tensor::data() const [with T = float]' is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
     float *ref_dev = ref.data<float>();
                                      ^
In file included from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/labuser/repos/object-posenet/lib/knn/src/cpu/vision.h:2,
                 from /home/labuser/repos/object-posenet/lib/knn/src/knn.h:2,
                 from /home/labuser/repos/object-posenet/lib/knn/src/vision.cpp:1:
/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:341:7: note: declared here
   T * data() const {
       ^~~~
In file included from /home/labuser/repos/object-posenet/lib/knn/src/vision.cpp:1:0:
/home/labuser/repos/object-posenet/lib/knn/src/knn.h:24:42: warning: 'T* at::Tensor::data() const [with T = float]' is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
     float *query_dev = query.data<float>();
                                          ^
In file included from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/labuser/repos/object-posenet/lib/knn/src/cpu/vision.h:2,
                 from /home/labuser/repos/object-posenet/lib/knn/src/knn.h:2,
                 from /home/labuser/repos/object-posenet/lib/knn/src/vision.cpp:1:
/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:341:7: note: declared here
   T * data() const {
       ^~~~
In file included from /home/labuser/repos/object-posenet/lib/knn/src/vision.cpp:1:0:
/home/labuser/repos/object-posenet/lib/knn/src/knn.h:25:36: warning: 'T* at::Tensor::data() const [with T = long int]' is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
     long *idx_dev = idx.data<long>();
                                    ^
In file included from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/labuser/repos/object-posenet/lib/knn/src/cpu/vision.h:2,
                 from /home/labuser/repos/object-posenet/lib/knn/src/knn.h:2,
                 from /home/labuser/repos/object-posenet/lib/knn/src/vision.cpp:1:
/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:341:7: note: declared here
   T * data() const {
       ^~~~
In file included from /home/labuser/repos/object-posenet/lib/knn/src/vision.cpp:1:0:
/home/labuser/repos/object-posenet/lib/knn/src/knn.h:30:16: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   if (ref.type().is_cuda()) {
                ^
In file included from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/labuser/repos/object-posenet/lib/knn/src/cpu/vision.h:2,
                 from /home/labuser/repos/object-posenet/lib/knn/src/knn.h:2,
                 from /home/labuser/repos/object-posenet/lib/knn/src/vision.cpp:1:
/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /home/labuser/repos/object-posenet/lib/knn/src/vision.cpp:1:0:
/home/labuser/repos/object-posenet/lib/knn/src/knn.h:38:45: error: 'THCState_getCurrentStream' was not declared in this scope
       dist_dev, idx_dev + b * k * query_nb, THCState_getCurrentStream(state));
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/labuser/repos/object-posenet/lib/knn/src/knn.h:38:45: note: suggested alternative: 'THCState_getCudaHostAllocator'
       dist_dev, idx_dev + b * k * query_nb, THCState_getCurrentStream(state));
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
                                             THCState_getCudaHostAllocator
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/labuser/repos/object-posenet/env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by mentian** [comment]
Sorry that I could not locate the problem from what you have provided. Are you compiling the code with ROS?

**Comment by TommasoBendinelli** [comment]
Not really. I was using a standard ubuntu machine.

**Comment by mentian** [comment]
My suggestions are:
(1) try to compile with the environment specified in README and check if the problem still exists
(2) provide more information on your environment (pytorch version, cuda version, ninja version, etc.), It would be easier for me to fix this problem if I can reproduce it. I suspect the problem is with ninja build system, which I have not tested before.
